version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: makas_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/app/uploads:/app/app/uploads
    environment:
      - PORT=${BACKEND_PORT}
    restart: unless-stopped
    networks:
      - makas_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: makas_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:${BACKEND_PORT}
      - PORT=${FRONTEND_PORT}
    restart: unless-stopped
    networks:
      - makas_network
    depends_on:
      - backend

networks:
  makas_network:
    driver: bridge