version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: makas_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/uploads:/app/app/uploads
    environment:
      - PORT=8000
    restart: unless-stopped
    networks:
      - makas_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: makas_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - PORT=3000
    restart: unless-stopped
    networks:
      - makas_network
    depends_on:
      - backend

networks:
  makas_network:
    driver: bridge